import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import './skills.style.css';
import tailwind from '../assets/images/tailwind-logo.png';
import typescript from '../assets/images/typescript-plain-icon-256x256-ypojgpyj.png';
import reactnative from '../assets/images/react_native_logo.png';
import nextjs from '../assets/images/next-js-icon.png';
import nodejs from '../assets/images/node_icon.png';
import mongodb from '../assets/images/mongodb_icon.png';
import firebase from '../assets/images/firebase_logo.png';
import hygraph from '../assets/images/hygraph-icon.png';
function Skills() {
    return (_jsx("div", { id: 'skills', className: 'mt-16 max-md:w-full lg:w-1/2', children: _jsx("div", { className: 'section-wrapper h-full', children: _jsxs("div", { className: 'p-10 bg-gray-900 rounded-3xl lg:mr-4 h-full', children: [_jsx("h2", { className: 'section-title text-left text-white', children: "Front-End Developer" }), _jsx("h3", { className: 'mt-2 text-lg text-left text-gray-400', children: "I combine over decade of experience in visual storytelling with software development. My proficiency lies in front-end engineering, complemented by a foundational understanding of back-end technologies." }), _jsxs("div", { className: "flex flex-wrap w-full max-sm:justify-between sm:gap-24 max-md:justify-left md:gap-24 lg:justify-left lg:gap-10", children: [_jsxs("div", { children: [_jsx("h2", { className: 'skills-title mt-8 mb-2  text-left text-white', children: "Front-End" }), _jsxs("ul", { className: 'text-lg text-gray-200 space-y-4', children: [_jsxs("li", { className: 'flex gap-4 align-center', children: [_jsx("img", { src: tailwind, width: 28, height: 28 }), "Tailwind"] }), _jsxs("li", { className: 'flex gap-4 align-center', children: [_jsx("img", { src: typescript, width: 28, height: 28 }), "TypeScript"] }), _jsxs("li", { className: 'flex gap-4 align-center', children: [_jsx("img", { src: reactnative, width: 28, height: 28 }), "ReactJS | Native"] }), _jsxs("li", { className: 'flex gap-4 align-center', children: [_jsx("img", { src: nextjs, width: 28, height: 28 }), "Next.js"] })] })] }), _jsxs("div", { children: [_jsx("h2", { className: 'skills-title mt-8 mb-2 text-left text-white', children: "Back-End" }), _jsxs("ul", { className: 'text-lg text-gray-200 space-y-4', children: [_jsxs("li", { className: 'flex gap-4 align-center', children: [_jsx("img", { src: nodejs, width: 28, height: 28 }), "Node | Express"] }), _jsxs("li", { className: 'flex gap-4 align-center', children: [_jsx("img", { src: mongodb, width: 28, height: 28 }), "MongoDB"] }), _jsxs("li", { className: 'flex gap-4 align-center', children: [_jsx("img", { src: firebase, width: 28, height: 28 }), "FireBase"] }), _jsxs("li", { className: 'flex gap-4 align-center', children: [_jsx("img", { src: hygraph, width: 28, height: 28 }), "Hygraph"] })] })] })] })] }) }) }));
}
export default Skills;
